### ISSUE TITLE
Dúvida sobre item 3 do artigo

### ISSUE THREAD

**Issue by DouglasHennrich** [Webschool-io/be-mean-instagram-mongodb-articles#2]
Fala @suissa !
Estou com uma dúvida... estou fazendo o artigo e pesquisando [no artigo que já foi entregue](https://github.com/Webschool-io/be-mean-instagram-mongodb-articles/blob/master/article-tiagodurante-TiagoAmadoDurante.md), eu notei que o item 3: Explique cada papel listado em [Cluster Administration Roles](https://docs.mongodb.org/manual/reference/built-in-roles/#cluster-administration-roles)
Não está de acordo com os papeis, roles, listados no site nessa área:
![captura de tela 2015-12-03 as 02 52 25](https://cloud.githubusercontent.com/assets/10107024/11552190/f6ff2bf4-9968-11e5-86eb-509debf010ce.png)

Pelo artigo do nosso amigo, eu não achei aquelas regras que ele postou no item 3. Será que o artigo dele está errado ou **EU** estou olhando no local errado e/ou não entendi direito o que era para apresentar?
Valeu =)

**Comment by suissa** [comment]
São todas as regras listadas ali que possuem link em azul https://docs.mongodb.org/manual/reference/built-in-roles/#cluster-administration-roles
